### PR TITLE
Document SnapshotItem

### PR DESCRIPTION
**Pull request by uint**

### CODE REVIEW

**Review by chipshort — COMMENTED** [review]
Percentages for prices seem a bit weird, but other than that I like this a lot.

**Comment by uint** [comment]
> Percentages for prices seem a bit weird, but other than that I like this a lot.

I had exchange rates in mind (and yeah, that probably wasn't clear), but would it be more natural to go with integers?

**Comment by uint** [comment]
Anyway, I'll change it one way or another.

**Comment by chipshort** [comment]
I think decimals are fine, just wouldn't refer to them as "x%"

**Review by chipshort — APPROVED** [review]
LGTM 👍

**Pull request merged**
