### PR TITLE
Add CI step to check links validity

### PR DESCRIPTION
**Pull request by aumetra**

### CODE REVIEW

**Comment by aumetra** [comment]
I swear, if this tool also doesn't work, I will just hack together another thing in Rust.

**Comment by aumetra** [comment]
> ℹ️ The file "*.mdx" specified in the config does not exist.

Rust time.

**Review by hashedone — APPROVED** [review]
Neat

**Comment by uint** [comment]
Oh hell yeah, I was wondering if we can get something like that in CI

**Comment by aumetra** [comment]
It only works for external links for now. Internal links would need something like running the NextJS page in the background and then running all the relative links against it

**Pull request merged**
