### PR TITLE
Testing contract written in Sylvia

### PR DESCRIPTION
**Pull request by DariuszDepta**

### CODE REVIEW

**Review by jawoznia — COMMENTED** [review]
Overall it's ok. Most of the comments refer to calling Sylvia attributes entry points.

**Comment by DariuszDepta** [comment]
image
I would agree if I were certain that, in real life, no additional 'integration tests' would be written by users. Placing our MT integration tests in a dedicated module could be a good practice to maintain a clear separation from other integration tests that users may wish to create. My preference is to keep this module as presented in the documentation. Advanced users will, in any case, place these tests wherever they deem appropriate.

**Comment by DariuszDepta** [comment]
image
Added links.
One comment, how to define the link, to directly open this: 
image

**Comment by DariuszDepta** [comment]
image
Added the link.

**Comment by DariuszDepta** [comment]
image
Updated as suggested.

**Comment by DariuszDepta** [comment]
image
Updated as suggested.

**Comment by jawoznia** [comment]
> image Added links. One comment, how to define the link, to directly open this: image

I don't see how to preset the `interface`. The `sylvia/macros/generated-types/multitest#proxy-trait` has to be enough.

**Comment by DariuszDepta** [comment]
image
Agree, updated as suggested.
All "ditto"s in this chapter also corrected as suggested.

**Review by jawoznia — APPROVED** [review]

**Pull request merged**
