### PR TITLE
Check if any tests contain entrypoints that don't contain the library feature

### LINKED ISSUE #67: Make sure all code examples containing an entry point use library feature
Follow-up to https://github.com/CosmWasm/docs/pull/57#discussion_r1648851578

We should probably enforce the convention of having a library feature in contracts by putting them explicitly into every code sample and reinforcing that this is *how it should be done*.

Also, as @chipshort mentioned, people will probably copy-paste from the docs a lot, so having that library feature everywhere means that they will follow best practices.

---

One open question is how to enforce this in CI. An idea I had was a simple CI step that greps across the extracted tests for `^#\[entry_point\]` and errors out when it gets hit (something like that)

### PR DESCRIPTION
**Pull request by aumetra**
Closes #67

### CODE REVIEW

**Comment by aumetra** [comment]
I love fighting bash

**Comment by aumetra** [comment]
Pardon my language, but is this CI FUCKING KIDDING ME?!  
This does *not* happen locally. I'm actually baffled.

**Comment by aumetra** [comment]
Why does it checkout this commit? `3de64047e0ca39af6910adc6537134009c302d72` (or tries to. I don't know.)

**Review by chipshort — APPROVED** [review]
LGTM

**Pull request merged**
