### PR TITLE
Core updates (part 2)

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Comment by aumetra** [comment]
Yeah, we need a CI update for that.. not sure if we can still have the check with a single ripgrep invocation, or if we need something more complicated.

**Comment by webmaster128** [comment]
No idea what the CI is complaining about here. Could you push a commit to fix that?

**Comment by aumetra** [comment]
It's the `entry_point` thing you fixed. The CI step checks through all MDX files to ensure nobody is writing `#[entry_point]` raw and always adds the library feature.

That was done in order to promote best practice. I'll have a look at the CI

**Comment by webmaster128** [comment]
Mybe we can just rephase like that to avoid the problem and make it more compact:

> So instead of using `#[entry_point]` directly, you should do this:

**Review by aumetra — APPROVED** [review]

**Comment by webmaster128** [comment]
Thanks!

**Pull request merged**
